name: 1.0$(rev:.r)

trigger:
  branches:
    include:
      - master 
  paths:
    exclude:
      - README.md
      - ci-ef-cosmos.yml
      - cd-ef-cosmos.yml

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.3'
  inputs:
    versionSpec: 4.9.3

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'src\**\*.sln'

- task: MSBuild@1
  displayName: 'Build beta'
  inputs:
    solution: src/Ef.Cosmos/Ef.Cosmos.csproj
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath=$(build.artifactstagingdirectory)/beta /p:AssemblyFileVersion=$(Build.BuildNumber)  '
    clean: true

- task: MSBuild@1
  displayName: 'Build final'
  inputs:
    solution: src/Ef.Cosmos/Ef.Cosmos.csproj
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath=$(build.artifactstagingdirectory)/final /p:AssemblyFileVersion=$(Build.BuildNumber) '
    clean: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'